services:
  - type: web
    name: Weatherbite
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: cd back-end && npm install
    startCommand: cd back-end && npm start
    envVars:
      - key: NODE_ENV
        value: production
