on: workflow_dispatch
name: Publish on Sites

jobs:
  netlify:
    name: Publish to Netlify
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Netlify
      uses: netlify/actions/cli@master
      with:
        args: deploy --build --prod --dir=./front-end
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
